/// VolumeRenderingReplacementsExport.h

#ifndef __VolumeRenderingReplacementsExport_h
#define __VolumeRenderingReplacementsExport_h

#define Q_SLICER_QTMODULES_VOLUMERENDERING_REPLACEMENTS_EXPORT

#endif // __VolumeRenderingReplacementsExport_h
